#!/usr/bin/env python3
"""Regenerate public/og.svg — the social preview card.

Only needed when the card's TEXT changes. The type is baked into the SVG as
outlines, so nothing here runs during a normal build: `node scripts/build-og.mjs`
rasterises the committed og.svg to og.png and needs no Python and no fonts.

Outlines rather than <text> because the brand faces (Anton, Space Grotesk) ship
as web fonts that fontconfig can't see, so a renderer would silently substitute
something else. Paths render identically everywhere.

Requires fonttools + brotli (Space Grotesk ships woff2). If they aren't on the
system Python, use a throwaway venv:
    python3 -m venv /tmp/ogvenv && /tmp/ogvenv/bin/pip install fonttools brotli
    /tmp/ogvenv/bin/python scripts/build-og-text.py
"""
import pathlib
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform
from fontTools.varLib import instancer

ROOT = pathlib.Path(__file__).resolve().parent.parent
ANTON = ROOT / "node_modules/@fontsource/anton/files/anton-latin-400-normal.woff"
GROTESK = ROOT / "node_modules/@fontsource-variable/space-grotesk/files/space-grotesk-latin-wght-normal.woff2"

# Site palette (src/styles/global.css). No gold — it was retired from the brand.
ACCENT, TEXT, MUTED, BG = "#1a8fd6", "#0e1116", "#2c303b", "#f7f7f3"

_cache = {}
def load(which, wght=400):
    key = (which, wght)
    if key not in _cache:
        if which == "anton":
            f = TTFont(ANTON)
        else:
            f = TTFont(GROTESK)
            if "fvar" in f:
                f = instancer.instantiateVariableFont(f, {"wght": wght})
        _cache[key] = f
    return _cache[key]

def text_path(text, which, size, x, y, wght=400, tracking=0.0):
    """SVG path data for `text`, baseline at (x, y). Advance widths only — no
    kerning, which at these sizes is not visible."""
    f = load(which, wght)
    upm = f["head"].unitsPerEm
    cmap, gs, hmtx = f.getBestCmap(), f.getGlyphSet(), f["hmtx"]
    scale = size / upm
    parts, cursor, missing = [], 0.0, []
    for ch in text:
        gname = cmap.get(ord(ch))
        if gname is None:
            missing.append(ch); cursor += 0.5 * upm; continue
        spen = SVGPathPen(gs)
        gs[gname].draw(TransformPen(spen, Transform(scale, 0, 0, -scale, x + cursor * scale, y)))
        if (d := spen.getCommands()):
            parts.append(d)
        cursor += hmtx[gname][0] + tracking * upm
    if missing:
        raise SystemExit(f"Font is missing glyphs for {missing!r} in {text!r}")
    return " ".join(parts), cursor * scale

W, H = 1200, 630
M = 84  # left margin

# Mirrors the homepage hero: first name solid, surname outlined.
lead_d, _ = text_path("Mohammed", "anton", 100, M, 286)
rest_d, _ = text_path("Akash", "anton", 100, M, 388)
hook_d, _ = text_path("moh·akash — “the infinite sky”", "grotesk", 27, M, 446, wght=500)
tag_d, _ = text_path("Web developer · researcher · poet — building in public with Claude.",
                     "grotesk", 23, M, 492, wght=400)
url_d, _ = text_path("mohakash.xyz", "grotesk", 26, M, 566, wght=600)

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}">
  <!-- Social preview card. Generated by scripts/build-og-text.py; the type is
       outlines, so this file renders the same anywhere. Rasterise with
       `node scripts/build-og.mjs`, which also composites the logo mark. -->
  <defs>
    <linearGradient id="sky" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{BG}"/>
      <stop offset="0.55" stop-color="#eef4fa"/>
      <stop offset="1" stop-color="#e3eef8"/>
    </linearGradient>
    <radialGradient id="glow" cx="0.5" cy="0.5" r="0.5">
      <stop offset="0" stop-color="{ACCENT}" stop-opacity="0.30"/>
      <stop offset="1" stop-color="{ACCENT}" stop-opacity="0"/>
    </radialGradient>
  </defs>

  <rect width="{W}" height="{H}" fill="url(#sky)"/>

  <!-- cosmic field, right side -->
  <circle cx="985" cy="300" r="250" fill="url(#glow)"/>
  <g fill="none" stroke="{ACCENT}" stroke-opacity="0.30">
    <ellipse cx="985" cy="300" rx="215" ry="88" transform="rotate(-24 985 300)"/>
    <ellipse cx="985" cy="300" rx="160" ry="160"/>
    <ellipse cx="985" cy="300" rx="92" ry="212" transform="rotate(18 985 300)"/>
  </g>
  <g fill="{ACCENT}" fill-opacity="0.55">
    <circle cx="806" cy="214" r="3.4"/><circle cx="1162" cy="356" r="3"/>
    <circle cx="1052" cy="128" r="2.6"/><circle cx="912" cy="474" r="3.2"/>
    <circle cx="1136" cy="206" r="2.2"/>
  </g>

  <!-- accent rule above the name -->
  <rect x="{M}" y="172" width="72" height="7" fill="{ACCENT}"/>

  <path d="{lead_d}" fill="{ACCENT}"/>
  <path d="{rest_d}" fill="none" stroke="{ACCENT}" stroke-width="2.4"/>
  <path d="{hook_d}" fill="{ACCENT}"/>
  <path d="{tag_d}" fill="{MUTED}"/>
  <path d="{url_d}" fill="{TEXT}"/>
</svg>
'''
out = ROOT / "public/og.svg"
out.write_text(svg, encoding="utf-8")
print(f"Wrote {out.relative_to(ROOT)} ({len(svg)} bytes)")
